### ISSUE TITLE
MMM_PlexNowPlaying is suspended

### ISSUE THREAD

**Issue by jadgsam** [youse/MMM-PlexNowPlaying#1]
Hi,
May be this question is very basic but I am getting the following error message

MMM-PlexNowPlaying.js:77 <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>

Plex in installed in the raspberry pi so I attempted to use the localhost ip address and the current one 192.168.1.3

I would appreciate your feedback.

Thanks in advance,
José

**Comment by youse** [comment]
That's going to be tough to debug without more information.  When you are playing something from the Plex server (you say it is on the RPi), can you visit the following URL from a web browser from within your local network:  http://192.168.1.3:32400/status/sessions

This is the URL that this module needs to talk to in order to get song information.
